# This is a basic workflow to help you get started with Actions

name: CI DEMO1
run-name: ${{ github.actor }} is learning GitHub Actions
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Stage:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🚥 The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2.0.0

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: Stage  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  test:
    needs: Stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          cat README.md
  check:
    needs: [build,Stage,test,pkg-bats-version]
    runs-on: ubuntu-latest
    steps:
      - name: Test another repo
        uses: DeveloperMetrics/deployment-frequency@main
        with:
          workflows: 'CI DEMO1'
          #owner-repo: 'DeveloperMetrics/DevOpsMetrics'
          #default-branch: 'main'
          number-of-days: 10
          actions-token: "${{ secrets.GITHUB_TOKEN }}"
      #- name: Workflow Telemetry
      #  uses: catchpoint/workflow-telemetry-action@v2.0.0

  pkg-bats-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x,14.x,16.x]
    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm install -g bats
        - run: bats -v